services:
  db-inzage:
    image: harbor-gn2.cicd.s15m.nl/ictu-devops-pub/cloudnative-pg/inzage/postgresql:15.2.18
    container_name: ${POSTGRES_DB}_postgres_db
    restart: always
    env_file:
      - backend/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    working_dir: /mnt
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - database
    environment:
      PGUSER: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: [ "postgres", "-c", "log_statement=all", "-p", "${POSTGRES_PORT}" ]

  dbgate:
    image: dbgate/dbgate:alpine
    container_name: dbgate
    volumes:
      - dbgate:/root/.dbgate
    depends_on:
      - db-inzage
    ports:
      - 8092:3000
    networks:
      - database
    environment:
      CONNECTIONS: PUBLIC

      LABEL_PUBLIC: ${POSTGRES_DB}
      SERVER_PUBLIC: 'db-inzage'
      USER_PUBLIC: ${POSTGRES_USER}
      PASSWORD_PUBLIC: ${POSTGRES_PASSWORD}
      PORT_PUBLIC: ${POSTGRES_PORT}
      ENGINE_PUBLIC: postgres@dbgate-plugin-postgres

  backend:
    build:
      context: .
      dockerfile: backend/Opensource.Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db-inzage
    networks:
      - database
    environment:
      POSTGRES_SERVER: db-inzage
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: >
      bash -c "echo 'allow postgres to start' && sleep 3 && 
      alembic -c alembic/alembic.ini upgrade head
      && uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-config=app/logging.conf"

  frontend:
    build:
      context: .
      dockerfile: frontend/Opensource.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend
    environment:
        NODE_ENV: ${NODE_ENV}
        VUE_APP_TITLE: ${VUE_APP_TITLE}
        VUE_APP_THEME: ${VUE_APP_THEME}
        VUE_APP_USE_AUTH: ${VUE_APP_USE_AUTH}

volumes:
  dbgate:
    name: inzage_dbgate
  postgres:
    name: ${POSTGRES_DB}

networks:
  database:
    external: true