import { Table } from '@/types/Tables'

const tables: Array<Table> = [
  {
    label: 'Besluiten',
    group: 'Besluiten',
    resource: 'evtp-version',
    nameKey: 'evtp_nm',
    primaryKey: 'evtp_cd',
    maxWidthDialog: 2000,
    columns: {
      evtp_cd: 'Code Besluit',
      evtp_nm: 'Naam Besluit',
      oe_best: 'Besluitnemende Oe',
      versie_nr: 'Versie nummer',
      id_publicatiestatus: 'Status Besluit',
      user_nm: 'ID redacteur',
      ts_mut: 'Tijdstip laatste mutatie',
      ts_publ: 'Publicatiedatum',
      notitie: 'Notitieveld',
      evtp_cd_sup: 'Code Besluit Hoger',
      omschrijving: 'Omschrijving Besluit',
      overige_informatie: 'Overige informatie',
      overige_informatie_link: 'Link overige informatie',
      uri: 'URI UPL',
      lidw_soort_besluit: 'Lidwoord soort besluit',
      soort_besluit: 'Soort besluit',
      aanleiding: 'Aanleiding besluit',
      gebr_dl: 'Gebruiksdoel gegevens',
      huidige_versie: 'Huidige versie',
    },
    hiddenColumns: [
      'omschrijving',
      'lidw_soort_besluit',
      'soort_besluit',
      'aanleiding',
      'gebr_dl',
      'huidige_versie',
      'uri',
    ],
    fieldOrder: [
      'evtp_cd',
      'huidige_versie',
      'evtp_cd_sup',
      'evtp_nm',
      'omschrijving',
      'uri',
      'lidw_soort_besluit',
      'soort_besluit',
      'oe_best',
      'aanleiding',
      'gebr_dl',
      'notitie',
      "overige_informatie",
      "overige_informatie_link",
      'user_nm',
      'ts_mut',
      'id_publicatiestatus',
      'ts_publ',
    ],
  },
  {
    label: 'Accorderingen',
    group: 'Besluiten',
    resource: 'evtp-acc',
    nameKey: 'evtp_cd',
    primaryKey: 'evtp_acc_cd',
    maxWidthDialog: 1160,
    columns: {
      evtp_acc_cd: 'Code besluit accordering',
      evtp_cd: 'Besluit',
      oe_cd: 'Accorderende Organisatie',
      ts_acc: 'Datum',
      notitie: 'Notitieveld',
      user_nm: 'ID Redacteur',
      volg_nr: 'Volgnummer',
      bestand_acc_cd: 'Code bestand',
    },
    hiddenColumns: [],
    fieldOrder: [
      'evtp_acc_cd',
      'evtp_cd',
      'oe_cd',
      'ts_acc',
      'notitie',
      'user_nm',
      'volg_nr',
      'bestand_acc_cd',
    ],
  },
  {
    label: 'Koppeling communicatiekanaal',
    group: 'Besluiten',
    resource: 'evtp-oe-com-type',
    nameKey: '',
    primaryKey: 'evtp_oe_com_type_cd',
    maxWidthDialog: 1160,
    columns: {
      evtp_oe_com_type_cd: 'Besluit organisatie code',
      evtp_cd: 'Besluit code',
      oe_com_type_cd: 'Communicatie kanaal type code',
      versie_nr: 'Besluit versie',
      link: 'Link',
      user_nm: 'ID Redacteur',
      ts_mut: 'Tijdstip laatste mutatie',
    },
    hiddenColumns: [],
    fieldOrder: [
      'evtp_oe_com_type_cd',
      'evtp_cd',
      'versie_nr',
      'oe_com_type_cd',
      'link',
      'user_nm',
      'ts_mut',
    ],
  },
  {
    label: 'Koppeling gegevensstroom',
    group: 'Besluiten',
    resource: 'evtp-gst',
    nameKey: 'Omschrijving',
    primaryKey: 'evtp_gst_cd',
    maxWidthDialog: 1160,

    columns: {
      evtp_gst_cd: 'Code evtp-gst',
      evtp_cd: 'Besluit',
      gst_cd: 'Gegevensstroom',
      versie_nr: 'Besluit versie',
      notitie: 'Notitieveld',
      conditie: 'Conditie',
      user_nm: 'ID Redacteur',
      ts_mut: 'Tijdstip laatste mutatie',
      sort_key: 'Sorteer sleutel',
    },
    hiddenColumns: [],
    fieldOrder: [
      'evtp_gst_cd',
      'evtp_cd',
      'versie_nr',
      'gst_cd',
      'notitie',
      'conditie',
      'user_nm',
      'ts_mut',
      'sort_key',
    ],
  },
  {
    label: 'Koppeling onderwerp',
    group: 'Besluiten',
    resource: 'evtp-ond',
    nameKey: '',
    primaryKey: 'evtp_ond_cd',
    maxWidthDialog: 1160,
    columns: {
      evtp_ond_cd: 'Onderwerpen code',
      ond_cd: 'Onderwerp titel',
      evtp_cd: 'Besluit omschrijving',
      versie_nr: 'Besluit versie',
      user_nm: 'ID Redacteur',
      notitie: 'Notitieveld',
      ts_mut: 'Tijdstip laatste mutatie',
    },
    hiddenColumns: [],
    fieldOrder: [
    'evtp_cd',
    'versie_nr',
    'ond_cd',
    'notitie',
    'user_nm',
    'ts_mut'
  ],
  },
  {
    label: 'Gegevensstromen',
    group: 'Gegevensstromen',
    resource: 'gst',
    nameKey: 'omschrijving',
    primaryKey: 'gst_cd',
    maxWidthDialog: 1160,
    columns: {
      gst_cd: 'Code gegevensstroom',
      gst_upc: 'UPC gegevensstroom',
      omschrijving: 'Omschrijving gegevensstroom',
      oe_bron: 'Bron Oe',
      oe_best: 'Afnemende Oe',
      ext_lnk_aut: 'Link naar autorisatiepagina',
      ibron_cd: 'Ibron',
      notitie: 'Notitieveld',
      user_nm: 'ID Redacteur',
      ts_mut: 'Tijdstip laatste mutatie',
    },
    hiddenColumns: ['ext_lnk_aut', 'ibron_cd', 'ts_mut'],
    fieldOrder: [
      'gst_cd',
      'gst_upc',
      'omschrijving',
      'oe_bron',
      'oe_best',
      'ext_lnk_aut',
      'ibron_cd',
      'notitie',
      'user_nm',
      'ts_mut',
    ],
  },
  {
    label: 'Gegevensstroomtype',
    group: 'Gegevensstromen',
    resource: 'gst-type',
    nameKey: 'gstt_naam',
    primaryKey: 'gstt_cd',
    maxWidthDialog: 1160,
    columns: {
      gstt_cd: 'Code type gst',
      gstt_naam: 'Naam type gst',
      gstt_oms: 'Korte omschrijving gst',
      notitie: 'Notitieveld',
      ts_mut: 'Tijdstip laatste mutatie',
      user_nm: 'ID Redacteur',
      gstt_pp: 'Push/Pull',
    },
    hiddenColumns: [],
    fieldOrder: [
      'gstt_cd',
      'gstt_naam',
      'gstt_oms',
      'notitie',
      'ts_mut',
      'user_nm',
      'gstt_pp',
    ],
  },
  {
    label: 'Koppeling gegevensgroep',
    group: 'Gegevensstromen',
    resource: 'gst-gg',
    nameKey: 'gg_cd',
    primaryKey: 'gst_gg_cd',
    maxWidthDialog: 1160,
    columns: {
      gst_gg_cd: 'Code gst-gg',
      gst_cd: 'Code gst',
      gg_cd: 'Code gg',
      versie_nr: 'Besluit versie',
      notitie: 'Notitieveld',
      user_nm: 'ID Redacteur',
      ts_mut: 'Tijdstip laatste mutatie',
      sort_key: 'Sorteersleutel',
    },
    hiddenColumns: [],
    fieldOrder: [
      'gst_gg_cd',
      'gst_cd',
      'versie_nr',
      'gg_cd',
      'notitie',
      'user_nm',
      'ts_mut',
      'sort_key',
    ],
  },
  {
    label: 'Koppeling gegevensstroomtype',
    group: 'Gegevensstromen',
    resource: 'gst-gstt',
    nameKey: 'gstt_naam',
    primaryKey: 'gst_gstt_cd',
    maxWidthDialog: 1160,
    columns: {
      gst_gstt_cd: 'Code gst gstt',
      gstt_cd: 'Code type gst',
      versie_nr: 'Besluit versie',
      gstt_naam: 'Naam type gst',
      gst_cd: 'Code gst',
      notitie: 'Notitieveld',
      user_nm: 'ID Redacteur',
      ts_mut: 'Tijdstip laatste mutatie',
    },
    hiddenColumns: [],
    fieldOrder: [
      'gst_gstt_cd',
      'gst_cd',
      'versie_nr',
      'gstt_cd',
      'notitie',
      'user_nm',
      'ts_mut',
    ],
  },
  {
    label: 'Koppeling wettelijke regelingen',
    group: 'Gegevensstromen',
    resource: 'gst-rge',
    nameKey: 'gst_cd',
    primaryKey: 'gst_rge_cd',
    maxWidthDialog: 1160,
    columns: {
      gst_rge_cd: 'Code gst-rge',
      gst_cd: 'Code gst',
      rge_cd: 'Code rge',
      versie_nr: 'Besluit versie',
      notitie: 'Notitieveld',
      user_nm: 'ID Redacteur',
      ts_mut: 'Tijdstip laatste mutatie',
      sort_key: 'Sorteersleutel',
    },
    hiddenColumns: [],
    fieldOrder: [
      'gst_rge_cd',
      'gst_cd',
      'versie_nr',
      'rge_cd',
      'notitie',
      'user_nm',
      'ts_mut',
      'sort_key',
    ],
  },
  {
    label: 'Gegevensgroepen',
    group: 'Gegevensgroepen',
    resource: 'gg',
    nameKey: 'omschrijving',
    primaryKey: 'gg_cd',
    maxWidthDialog: 1160,
    columns: {
      gg_cd: 'Code gg',
      gg_upc: 'UPC gegevensgroep',
      omschrijving: 'Naam gg',
      notitie: 'Notitieveld',
      omschrijving_uitgebreid: 'Omschrijving gg',
      sort_key: 'Sorteer sleutel',
      user_nm: 'ID Redacteur',
      ts_mut: 'Tijdstip laatste mutatie',
      koepel: 'Selecteer of het een koepel is',
    },
    hiddenColumns: ['koepel'],
    fieldOrder: [
      'gg_cd',
      'gg_upc',
      'omschrijving',
      'notitie',
      'omschrijving_uitgebreid',
      'sort_key',
      'koepel',
      'user_nm',
      'ts_mut',
    ],
  },
  {
    label: 'Gegevensgroepen koepel',
    group: 'Gegevensgroepen',
    resource: 'gg-koepel',
    nameKey: 'omschrijving',
    primaryKey: 'gg_cd',
    maxWidthDialog: 1160,
    columns: {
      gg_cd: 'Code gg',
      gg_upc: 'UPC gegevensgroep',
      omschrijving: 'Naam gg',
      notitie: 'Notitieveld',
      omschrijving_uitgebreid: 'Omschrijving gg',
      sort_key: 'Sorteer sleutel',
      user_nm: 'ID Redacteur',
      ts_mut: 'Tijdstip laatste mutatie',
      koepel: 'Selecteer of het een koepel is',
    },
    hiddenColumns: ['koepel'],
    fieldOrder: [
      'gg_cd',
      'gg_upc',
      'omschrijving',
      'notitie',
      'omschrijving_uitgebreid',
      'sort_key',
      'koepel',
      'user_nm',
      'ts_mut',
    ],
  },
  {
    label: 'Gegevensgroepenstructuur',
    group: 'Gegevensgroepen',
    resource: 'gg-struct',
    nameKey: 'ID',
    primaryKey: 'gg_struct_cd',
    maxWidthDialog: 1160,
    columns: {
      gg_struct_cd: 'Code gg structuur',
      gg_cd_sub: 'Code gg lager',
      gg_cd_sup: 'Code gg hoger',
      notitie: 'Notitieveld',
      user_nm: 'ID redacteur',
      ts_mut: 'Tijdstip laatste mutatie',
    },
    hiddenColumns: ['ts_mut'],
    fieldOrder: [
      'gg_struct_cd',
      'gg_cd_sub',
      'gg_cd_sup',
      'notitie',
      'user_nm',
      'ts_mut',
    ],
  },
  {
    label: 'Gegevensgroep sortering per besluit',
    group: 'Gegevensgroepen',
    resource: 'gg-evtp-sort',
    nameKey: 'evtp_cd',
    primaryKey: 'gg_evtp_sort_cd',
    maxWidthDialog: 1160,
    columns: {
      gg_evtp_sort_cd: 'Code koppeling',
      evtp_cd: 'Besluit',
      gg_cd: 'Gegevensgroep',
      sort_key: 'Sorteersleutel',
      user_nm: 'ID Redacteur',
      ts_mut: 'Tijdstip laatste mutatie',
    },
    hiddenColumns: [],
    fieldOrder: [
      'gg_evtp_sort_cd',
      'evtp_cd',
      'gg_cd',
      'sort_key',
      'user_nm',
      'ts_mut',
    ],
  },
  {
    label: 'Organisaties',
    group: 'Organisaties',
    resource: 'oe',
    nameKey: 'naam_officieel',
    primaryKey: 'oe_cd',
    maxWidthDialog: 1160,
    columns: {
      oe_cd: 'Code OE',
      oe_upc: 'UPC organisatie',
      naam_officieel: 'Lange naam',
      naam_spraakgbr: 'Korte naam',
      afko: 'Afkorting OE',
      lidw_sgebr: 'Lidwoord OE',
      notitie: 'Toelichting',
      straat: 'Straatnaam/postbus',
      huisnummer: 'Huisnummer',
      huisnummer_toev: 'Toevoeging huisnummer',
      postcode: 'Postcode (Nederlands)',
      plaats: 'Plaats',
      provincie: 'Provincie',
      telefoon: 'Telefoonnummer',
      internet_domein: 'Domeinnaam internet',
      e_contact: 'Link Mijn-omgeving',
      user_nm: 'ID redacteur',
      ts_mut: 'Tijdstip laatste mutatie',
      ibron_cd: 'Informatiebron',
    },
    fieldOrder: [
      'oe_cd',
      'oe_upc',
      'naam_officieel',
      'naam_spraakgbr',
      'afko',
      'lidw_sgebr',
      'notitie',
      'straat',
      'huisnummer',
      'huisnummer_toev',
      'postcode',
      'plaats',
      'provincie',
      'telefoon',
      'internet_domein',
      'e_contact',
      'user_nm',
      'ts_mut',
      'ibron_cd',
    ],
    hiddenColumns: [
      'straat',
      'afko',
      'lidw_sgebr',
      'internet_domein',
      'notitie',
      'postcode',
      'provincie',
      'telefoon',
      'e_contact',
      'huisnummer',
      'huisnummer_toev',
      'plaats',
      'ts_mut',
      'ibron_cd',
    ],
  },
  {
    label: 'Organisatiestructuur',
    group: 'Organisaties',
    resource: 'oe-struct',
    nameKey: 'oe_cd_sup',
    primaryKey: 'oe_struct_cd',
    maxWidthDialog: 1160,
    columns: {
      oe_struct_cd: 'Code oe structuur',
      oe_cd_sup: 'Code hogere OE',
      oe_cd_sub: 'Code lagere OE',
      notitie: 'Notitieveld',
      user_nm: 'ID Redacteur',
      ts_mut: 'Tijdstip laatste mutatie',
    },
    hiddenColumns: ['ts_mut'],
    fieldOrder: [
      'oe_struct_cd',
      'oe_cd_sup',
      'oe_cd_sub',
      'koepel',
      'notitie',
      'user_nm',
      'ts_mut',
    ],
  },
  // placeholder for the group overig
  {
    label: '',
    group: 'Overig',
    resource: '',
    nameKey: '',
    primaryKey: '',
    maxWidthDialog: 0,
    columns: {},
    hiddenColumns: [],
    fieldOrder: [],
  },
  {
    label: 'Communicatiekanalen',
    group: 'Overig',
    resource: 'oe-com-type',
    nameKey: 'omschrijving',
    primaryKey: 'oe_com_type_cd',
    maxWidthDialog: 1160,
    columns: {
      oe_com_type_cd: 'Communicatie kanaal type code',
      omschrijving: 'Kanaal omschrijving',
      user_nm: 'ID Redacteur',
      notitie: 'Notitieveld',
      ts_mut: 'Tijdstip laatste mutatie',
    },
    hiddenColumns: [],
    fieldOrder: [
      'oe_com_type_cd',
      'omschrijving',
      'user_nm',
      'notitie',
      'ts_mut',
    ],
  },
  {
    label: 'Infobronnen',
    group: 'Overig',
    resource: 'ibron',
    nameKey: 'omschrijving',
    primaryKey: 'ibron_cd',
    maxWidthDialog: 1160,
    columns: {
      ibron_cd: 'Ibron',
      omschrijving: 'Naam van de bron',
      oe_cd: 'Code OE uitgever',
      user_nm: 'ID Redacteur',
      notitie: 'Notitieveld',
      ts_mut: 'Tijdstip laatste mutatie',
    },
    hiddenColumns: [],
    fieldOrder: [
      'ibron_cd',
      'omschrijving',
      'oe_cd',
      'notitie',
      'user_nm',
      'ts_mut',
    ],
  },
  {
    label: 'Onderwerpen',
    group: 'Overig',
    resource: 'ond',
    nameKey: 'titel',
    primaryKey: 'ond_cd',
    maxWidthDialog: 1160,
    columns: {
      ond_cd: 'Onderwerpen code',
      titel: 'Onderwerp titel',
      omschrijving: 'Onderwerp omschrijving',
      sort_key: 'Sorteer sleutel',
      user_nm: 'ID Redacteur',
      notitie: 'Notitieveld',
      ts_mut: 'Tijdstip laatste mutatie',
    },
    hiddenColumns: [],
    fieldOrder: [
      'ond_cd',
      'titel',
      'omschrijving',
      'sort_key',
      'notitie',
      'user_nm',
      'ts_mut',
    ],
  },
  {
    label: 'Wettelijke regelingen',
    group: 'Overig',
    resource: 'rge',
    nameKey: 'titel',
    primaryKey: 'rge_cd',
    maxWidthDialog: 1160,
    columns: {
      rge_cd: 'Code regelingselement',
      titel: 'Naam regeling',
      tekst: 'Officiële naam regeling',
      user_nm: 'ID Redacteur',
      notitie: 'Notitieveld',
      re_link: 'Link naar basiswettenbestand',
      ts_mut: 'Tijdstip laatste mutatie',
    },
    hiddenColumns: [],
    fieldOrder: [
      'rge_cd',
      'titel',
      'tekst',
      're_link',
      'notitie',
      'user_nm',
      'ts_mut',
    ],
  },
]

export { tables }
