repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        name: ruff check
        entry: bash -c 'cd backend && poetry run ruff check app --fix && poetry run ruff check tests --fix'
        language: python
        types: [python]
      - id: ruff-format
        name: ruff format
        entry: bash -c 'cd backend && poetry run ruff format app && poetry run ruff format tests'
        language: python
        types: [python]
  # - repo: local
  #   hooks:
  #   -   id: coverage
  #       name: backend-test-coverage
  #       stages: [commit]
  #       language: system
  #       entry: bash
  #       types: [python]
  #       pass_filenames: false
  #       args:
  #         - -c
  #         - |
  #           cd backend && poetry run coverage run -m pytest && poetry run coverage report
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: 'v9.1.1'  # Use the sha / tag you want to point at
  #   hooks:
  #     - id: eslint
  #       files:  \.(vue|[jt]sx?)$  # *.js, *.jsx, *.ts and *.tsx
  #       types: [file]
  #       args: ['--fix']