"""removed unused tables, added metadata and comments

Revision ID: 5373d4030cf2
Revises: 0836fc8fa349
Create Date: 2024-03-06 16:54:21.811556

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5373d4030cf2"
down_revision = "0836fc8fa349"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS persoon")
    op.execute("ALTER TABLE rubriekenvoorbeheer DROP CONSTRAINT IF EXISTS rubriektabel_fk")
    op.drop_index("ix_rubriekenvoorbeheer_tabelnaam", table_name="rubriekenvoorbeheer")
    op.drop_table("rubriekenvoorbeheer")
    op.drop_index("ix_tabellenvoorbeheer_tabelnaam", table_name="tabellenvoorbeheer")
    op.drop_table("tabellenvoorbeheer")
    op.drop_constraint("oes_osrt_fk", "oe_struct", type_="foreignkey")
    op.drop_table("oe_struct_rolt")
    op.drop_constraint("oe_oet_fk", "oe", type_="foreignkey")
    op.drop_table("oe_type")
    op.add_column(
        "bestand_acc",
        sa.Column("user_nm", sa.VARCHAR(length=30), server_default="ICTU", nullable=True, comment="Gebruikersnaam"),
    )
    op.alter_column(
        "bestand_acc",
        "bestand_acc_cd",
        existing_type=sa.INTEGER(),
        comment="Bestandsaccordering code",
        existing_nullable=False,
    )
    op.alter_column(
        "bestand_acc",
        "volg_nr",
        existing_type=sa.INTEGER(),
        comment="Volgnummer voor meerdere bestanden bij een accordering",
        existing_comment="Volgnummer",
        existing_nullable=False,
    )
    op.alter_column(
        "bestand_acc",
        "omschrijving",
        existing_type=sa.VARCHAR(length=255),
        comment="Bestandsomschrijving",
        existing_comment="Bestand omschrijving",
        existing_nullable=True,
    )
    op.alter_column(
        "bestand_acc",
        "bestand_verwijzing",
        existing_type=sa.VARCHAR(length=255),
        comment="Bestandsverwijzing",
        existing_comment="Betandsverwijzing",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp",
        "evtp_cd",
        existing_type=sa.INTEGER(),
        comment="Besluit code",
        existing_nullable=False,
        existing_server_default=sa.text("nextval('evtp_evtp_cd_seq'::regclass)"),
    )
    op.alter_column(
        "evtp",
        "evtp_upc",
        existing_type=sa.INTEGER(),
        comment="Uniforme product code dat hoort bij een besluit",
        existing_nullable=False,
    )
    op.create_index(op.f("ix_evtp_evtp_upc"), "evtp", ["evtp_upc"], unique=False)
    op.create_table_comment(
        "evtp",
        "Alle unieke besluiten met zijn bijgehorende uniforme product code nummer",
        existing_comment="Relevante soorten gebeurtenissen die aanleiding (kunnen) zijn voor het vastleggen of uitwisslen van gegevens(groepen)",
        schema=None,
    )
    op.add_column(
        "evtp_acc",
        sa.Column("user_nm", sa.VARCHAR(length=30), server_default="ICTU", nullable=True, comment="Gebruikersnaam"),
    )
    op.alter_column(
        "evtp_acc",
        "evtp_acc_cd",
        existing_type=sa.INTEGER(),
        comment="Accordering code",
        existing_nullable=False,
    )
    op.alter_column("evtp_acc", "evtp_cd", existing_type=sa.INTEGER(), comment="Besluit code", existing_nullable=False)
    op.alter_column(
        "evtp_acc", "oe_cd", existing_type=sa.INTEGER(), comment="Organisatie code", existing_nullable=False
    )
    op.alter_column(
        "evtp_acc",
        "volg_nr",
        existing_type=sa.INTEGER(),
        comment="Volgnummer mocht een accordering uit meerdere bestaan",
        existing_comment="Volgnummer",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_acc",
        "bestand_acc_cd",
        existing_type=sa.INTEGER(),
        comment="Bestandsaccordering code",
        existing_nullable=False,
    )
    op.drop_constraint("evtp_acc_cd_fk", "evtp_acc", type_="foreignkey")
    op.alter_column(
        "evtp_gst",
        "evtp_gst_cd",
        existing_type=sa.INTEGER(),
        comment="Besluit gegevensstroom code",
        existing_nullable=False,
    )
    op.alter_column("evtp_gst", "evtp_cd", existing_type=sa.INTEGER(), comment="Besluit code", existing_nullable=False)
    op.alter_column(
        "evtp_gst", "gst_cd", existing_type=sa.INTEGER(), comment="Gegevensstroom code", existing_nullable=False
    )
    op.alter_column(
        "evtp_gst",
        "conditie",
        existing_type=sa.VARCHAR(length=4000),
        comment="Toelichting van een conditie waaronder de gegevensstroom plaatsvindt, bijvoorbeeld ziek worden, wel of geen werk hebben, etc.",
        existing_comment="Toelichting van een conditie waaronder de gegevensstroom plaatsvindt, bijvoorbeeld ziek worden, wel of geen werk hebben, etc ",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_gst",
        "sort_key",
        existing_type=sa.INTEGER(),
        comment="Sorteersleutel om de gegevensstromen blokken te ordenen binnen een koepelgegeven van een besluit",
        existing_comment="Sorteersleutel",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_gst",
        "notitie",
        existing_type=sa.VARCHAR(length=4000),
        comment="Notitieveld",
        existing_comment="Notitie",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_gst",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        comment="Gebruikersnaam",
        existing_comment="User identification",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "evtp_gst",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "evtp_gst",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.drop_constraint("evtpgst_evtp_fk", "evtp_gst", type_="foreignkey")
    op.create_table_comment(
        "evtp_gst",
        "Koppeling tussen een besluit en de gegevensstromen",
        existing_comment="Cross-reference tusen gegevensstroom en eventtypen",
        schema=None,
    )
    op.add_column(
        "evtp_oe_com_type", sa.Column("notitie", sa.VARCHAR(length=4000), nullable=True, comment="Notitieveld")
    )
    op.alter_column(
        "evtp_oe_com_type",
        "evtp_oe_com_type_cd",
        existing_type=sa.INTEGER(),
        comment="Besluit bestemmingsorganisatie communicatie kanaal code",
        existing_comment="Besluit organisatie code",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_oe_com_type",
        "evtp_cd",
        existing_type=sa.INTEGER(),
        comment="Besluit code",
        existing_comment="Eventtype code",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_oe_com_type",
        "oe_com_type_cd",
        existing_type=sa.INTEGER(),
        comment="Communicatiekanaal type code",
        existing_comment="Kanaal type code",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_oe_com_type",
        "link",
        existing_type=sa.VARCHAR(length=2000),
        comment="Hyperlink waar de burger de uitkomst van het besluit ontvangt",
        existing_comment="Hyperlink waar de burger de uitkoms van het besluit ontvangt",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_oe_com_type",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        comment="Gebruikersnaam",
        existing_comment="User identification",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "evtp_oe_com_type",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "evtp_oe_com_type",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.drop_constraint("evtp_oe_com_evtp_fk", "evtp_oe_com_type", type_="foreignkey")
    op.create_table_comment(
        "evtp_oe_com_type",
        "Koppeling tussen een besluit en bestemmingsorganisatie communicatie kanaal",
        existing_comment="Relatie tussen besluit en bestemming organiatie communicatie kanaal",
        schema=None,
    )
    op.alter_column(
        "evtp_ond",
        "evtp_cd",
        existing_type=sa.INTEGER(),
        comment="Besluit code",
        existing_comment="Event type code",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_ond",
        "notitie",
        existing_type=sa.VARCHAR(length=2000),
        type_=sa.VARCHAR(length=4000),
        existing_comment="Notitieveld",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_ond",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        comment="Gebruikersnaam",
        existing_comment="User identification",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "evtp_ond",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
        comment="Tijdstip start datum",
        existing_comment="Tijdstip aanmaakdatum",
        existing_nullable=False,
    )
    op.drop_constraint("evptond_evtp_fk", "evtp_ond", type_="foreignkey")
    op.create_table_comment(
        "evtp_ond",
        "Koppeling tussen onderwerpen en besluiten",
        existing_comment="Relatie tussen onderwerpen en besluiten",
        schema=None,
    )
    op.alter_column(
        "evtp_version", "evtp_cd", existing_type=sa.INTEGER(), comment="Besluit code", existing_nullable=False
    )
    op.alter_column(
        "evtp_version",
        "versie_nr",
        existing_type=sa.INTEGER(),
        comment="Versie nummer van het besluit",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_version", "evtp_cd_sup", existing_type=sa.INTEGER(), comment="Koepelbesluit", existing_nullable=True
    )
    op.alter_column(
        "evtp_version",
        "evtp_nm",
        existing_type=sa.VARCHAR(length=200),
        comment="Naam van besluit",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_version",
        "omschrijving",
        existing_type=sa.VARCHAR(length=2000),
        comment="Omschrijving het besluit",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_version",
        "aanleiding",
        existing_type=sa.VARCHAR(length=2000),
        comment="Aanleiding van het nemen van een besluit",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_version",
        "gebr_dl",
        existing_type=sa.VARCHAR(length=200),
        comment="Gebruiksdoel van het besluit",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_version",
        "oe_best",
        existing_type=sa.INTEGER(),
        comment="Verantwoordelijke(=bestemming) organisatie die behoort tot dit besluit",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_version",
        "lidw_soort_besluit",
        existing_type=sa.VARCHAR(length=12),
        comment="Lidwoord van het soort besluit",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_version",
        "soort_besluit",
        existing_type=sa.VARCHAR(length=50),
        comment="Verschillende soorten officiële besluiten, mededelingen en documenten.",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_version",
        "huidige_versie",
        existing_type=sa.BOOLEAN(),
        comment="Wel of geen huidige versie van besluit",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "evtp_version",
        "id_publicatiestatus",
        existing_type=sa.INTEGER(),
        comment="Publicatie nummer voor een besluit",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_version", "notitie", existing_type=sa.VARCHAR(length=4000), comment="Notitieveld", existing_nullable=True
    )
    op.alter_column(
        "evtp_version",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        comment="Gebruikersnaam",
        existing_comment="User identification",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "evtp_version",
        "ts_mut",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip laatste mutatie",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "evtp_version",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "evtp_version",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.execute("DROP INDEX IF EXISTS ix_evtp_version_evtp_cd")
    op.drop_constraint("evpt_evptsup_fk", "evtp_version", type_="foreignkey")
    op.create_table_comment(
        "evtp_version",
        "Versie van een ieder besluit met een bepaalde status die aanleiding kunnen zijn voor het vastleggen of uitwisselen van gegevensgroepen",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "gg",
        "gg_cd",
        existing_type=sa.INTEGER(),
        comment="Gegevensgroep code",
        existing_nullable=False,
    )
    op.alter_column(
        "gg",
        "gg_upc",
        existing_type=sa.INTEGER(),
        nullable=False,
        comment="Uniforme product code dat hoort bij een gegevensgroep",
    )
    op.alter_column(
        "gg",
        "omschrijving",
        existing_type=sa.VARCHAR(length=4000),
        comment="Naam van de gegevensgroep",
        existing_comment="Omschrijving/Naam van de gegevensgroep",
        existing_nullable=False,
    )
    op.alter_column(
        "gg",
        "omschrijving_uitgebreid",
        existing_type=sa.VARCHAR(length=4000),
        comment="Uitgebreide omschrijving van de gegevensgroep",
        existing_comment="Notitieveld",
        existing_nullable=False,
    )
    op.alter_column(
        "gg",
        "sort_key",
        existing_type=sa.INTEGER(),
        comment="Sorteer volgorde van de koepelgegevensgroep in een besluit",
        existing_nullable=True,
    )
    op.alter_column("gg", "koepel", existing_type=sa.BOOLEAN(), comment="Wel of geen koepel", existing_nullable=True)
    op.alter_column(
        "gg",
        "notitie",
        existing_type=sa.VARCHAR(length=2000),
        type_=sa.VARCHAR(length=4000),
        comment="Notitieveld",
        existing_comment="Kort toelichting ter duiding van een gegevensgroep",
        existing_nullable=True,
    )
    op.alter_column(
        "gg",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        comment="Gebruikersnaam",
        existing_comment="User identification",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "gg",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gg",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.create_index(op.f("ix_gg_gg_upc"), "gg", ["gg_upc"], unique=False)
    op.alter_column(
        "gg_struct",
        "gg_struct_cd",
        existing_type=sa.INTEGER(),
        comment="Gegevensgroepen structuur code",
        existing_nullable=False,
    )
    op.alter_column(
        "gg_struct",
        "gg_cd_sub",
        existing_type=sa.INTEGER(),
        comment="Sub (child) gegevensgroep code",
        existing_nullable=False,
    )
    op.alter_column(
        "gg_struct",
        "gg_cd_sup",
        existing_type=sa.INTEGER(),
        comment="Super (parent) gegevensgroep code",
        existing_nullable=False,
    )
    op.alter_column(
        "gg_struct",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        comment="Gebruikersnaam",
        existing_comment="User identification",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "gg_struct",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gg_struct",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.create_table_comment(
        "gg_struct",
        "Hiërarchische structuur van gegevensgroepen wat resulteert in een sub(=child)-sup(=parent) relatie",
        existing_comment="Relatie tussen gegevensgroepen van een bepaalse soort",
        schema=None,
    )
    op.alter_column(
        "gst",
        "gst_cd",
        existing_type=sa.INTEGER(),
        comment="Gegevensstroom code",
        existing_nullable=False,
    )
    op.alter_column(
        "gst",
        "gst_upc",
        existing_type=sa.INTEGER(),
        comment="Uniforme product code dat hoort bij een gegevensstroom",
        existing_nullable=False,
    )
    op.alter_column(
        "gst",
        "omschrijving",
        existing_type=sa.VARCHAR(length=255),
        comment="Omschrijving van de gegevensstroom",
        existing_comment="Omschrijving/Naam gegevensstroom",
        existing_nullable=False,
    )
    op.alter_column(
        "gst", "oe_bron", existing_type=sa.INTEGER(), comment="Organisatorische eenheid bron", existing_nullable=False
    )
    op.alter_column(
        "gst",
        "oe_best",
        existing_type=sa.INTEGER(),
        comment="Organisatorische eenheid bestemming",
        existing_nullable=False,
    )
    op.alter_column(
        "gst",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        comment="Gebruikersnaam",
        existing_comment="User identification",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "gst",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gst",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.create_index(op.f("ix_gst_gst_upc"), "gst", ["gst_upc"], unique=False)
    op.create_table_comment(
        "gst",
        "Gegevensstroom die tussen bron- en bestemmingsorganisatorische eenheden loopt waarbij gegevensgroepen worden gedeeld",
        existing_comment="Gegevensstromen tussen (soorten) organisatorische eenheden/instanties",
        schema=None,
    )
    op.alter_column(
        "gst_gg_rge",
        "gst_gg_rge_cd",
        existing_type=sa.INTEGER(),
        comment="Gegevensstroom gegevensgroep regelingelement code",
        existing_nullable=False,
    )
    op.alter_column(
        "gst_gg_rge", "gst_cd", existing_type=sa.INTEGER(), comment="Gegevensstroom code", existing_nullable=False
    )
    op.alter_column(
        "gst_gg_rge", "gg_cd", existing_type=sa.INTEGER(), comment="Gegevensgroep code", existing_nullable=False
    )
    op.alter_column(
        "gst_gg_rge", "rge_cd", existing_type=sa.INTEGER(), comment="Regelingelement code", existing_nullable=False
    )
    op.alter_column(
        "gst_gg_rge",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        comment="Gebruikersnaam",
        existing_comment="User identification",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "gst_gg_rge",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gst_gg_rge",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.create_index(op.f("ix_gst_gg_rge_gg_cd"), "gst_gg_rge", ["gg_cd"], unique=False)
    op.create_index(op.f("ix_gst_gg_rge_gst_cd"), "gst_gg_rge", ["gst_cd"], unique=False)
    op.create_index(op.f("ix_gst_gg_rge_rge_cd"), "gst_gg_rge", ["rge_cd"], unique=False)
    op.create_table_comment(
        "gst_gg_rge",
        "Koppeling tussen gegevensstroom, gegevensgroep en regelingelemen",
        existing_comment="Relatie tussen gegevensstroom, gegevensgroep en wettelijke grondslag",
        schema=None,
    )
    op.add_column("gst_gstt", sa.Column("notitie", sa.VARCHAR(length=4000), nullable=True, comment="Notitieveld"))
    op.alter_column(
        "gst_gstt",
        "gst_gstt_cd",
        existing_type=sa.INTEGER(),
        comment="Gegevensstroom gegevensstroomtype code",
        existing_nullable=False,
    )
    op.alter_column(
        "gst_gstt", "gstt_cd", existing_type=sa.INTEGER(), comment="Gegevensstroomtype code", existing_nullable=False
    )
    op.alter_column(
        "gst_gstt", "gst_cd", existing_type=sa.INTEGER(), comment="Gegevensstroom code", existing_nullable=False
    )
    op.alter_column(
        "gst_gstt",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        comment="Gebruikersnaam",
        existing_comment="User identification",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "gst_gstt",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gst_gstt",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.create_table_comment(
        "gst_gstt",
        "Koppeling tussen gegevensstroom en gegevensstroomtype",
        existing_comment="Relatie tussen gegevensstroom en gegevensstroomtype",
        schema=None,
    )
    op.add_column("gst_type", sa.Column("notitie", sa.VARCHAR(length=4000), nullable=True, comment="Notitieveld"))
    op.alter_column(
        "gst_type",
        "gstt_cd",
        existing_type=sa.INTEGER(),
        comment="Gegevensstroomtype code",
        existing_nullable=False,
    )
    op.alter_column(
        "gst_type",
        "gstt_pp",
        existing_type=sa.VARCHAR(length=20),
        comment="Push of pull van een gegevenstroom type",
        existing_nullable=True,
    )
    op.alter_column(
        "gst_type",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        comment="Gebruikersnaam",
        existing_comment="User identification",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "gst_type",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gst_type",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.alter_column(
        "ibron",
        "ibron_cd",
        existing_type=sa.INTEGER(),
        comment="Informatiebron code",
        existing_nullable=False,
        existing_server_default=sa.text("nextval('ibron_ibron_cd_seq'::regclass)"),
    )
    op.alter_column("ibron", "oe_cd", existing_type=sa.INTEGER(), comment="Organisatie code", existing_nullable=True)
    op.alter_column(
        "ibron",
        "omschrijving",
        existing_type=sa.VARCHAR(length=80),
        comment="Omschrijving van de bron",
        existing_comment="Omschrijving/naam van de bron",
        existing_nullable=False,
    )
    op.alter_column(
        "ibron",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        comment="Gebruikersnaam",
        existing_comment="User identification",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "ibron",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "ibron",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.create_table_comment(
        "ibron",
        "register waar de gegevens afkomstig van zijn",
        existing_comment="Registratie waar de gegevens afkomstig van zijn.",
        schema=None,
    )
    op.alter_column(
        "oe",
        "oe_cd",
        existing_type=sa.INTEGER(),
        comment="Organisatie code",
        existing_nullable=False,
        existing_server_default=sa.text("nextval('oe_oe_cd_seq'::regclass)"),
    )
    op.alter_column("oe", "oe_upc", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "oe",
        "fax",
        existing_type=sa.VARCHAR(length=30),
        comment="Faxnummer",
        existing_comment="Faxnummer (volledig)",
        existing_nullable=True,
    )
    op.alter_column(
        "oe",
        "huisnummer",
        existing_type=sa.VARCHAR(length=10),
        comment="Huisnummer",
        existing_comment="Huisnummer cf. postcode tabel",
        existing_nullable=True,
    )
    op.alter_column("oe", "ibron_cd", existing_type=sa.INTEGER(), comment="Informatiebron code", existing_nullable=True)
    op.alter_column(
        "oe",
        "lidw_sgebr",
        existing_type=sa.VARCHAR(length=12),
        comment="Lidwoord van de organisatie",
        existing_comment="Lidwoord van de organisatie (de, het, een)",
        existing_nullable=True,
    )
    op.alter_column(
        "oe",
        "naam_spraakgbr",
        existing_type=sa.VARCHAR(length=255),
        comment="Naam die gebruikt voor in het 'normale' spraakgebruik",
        existing_comment="Naam die gebruikt voor in het 'normale'  spraakgebruik",
        existing_nullable=False,
    )
    op.alter_column(
        "oe",
        "straat",
        existing_type=sa.VARCHAR(length=30),
        comment="Straatnaam",
        existing_comment="Straatnaam cf. postcode tabel of 'Postbus'",
        existing_nullable=True,
    )
    op.alter_column(
        "oe",
        "telefoon",
        existing_type=sa.VARCHAR(length=30),
        comment="Telefoonnummer",
        existing_comment="Telefoonnummer (volledig)",
        existing_nullable=True,
    )
    op.alter_column(
        "oe",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        comment="Gebruikersnaam",
        existing_comment="User identification",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "oe",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "oe",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.create_table_comment(
        "oe",
        "Organisatorische eenheid en of instantie",
        existing_comment="Organisatorische eenheid/instantie of soort van organisatorische entiteit",
        schema=None,
    )
    op.drop_column("oe", "oe_type_cd")
    op.alter_column(
        "oe_com_type",
        "oe_com_type_cd",
        existing_type=sa.INTEGER(),
        comment="Communicatiekanaal type code",
        existing_comment="Kanaal type code",
        existing_nullable=False,
        existing_server_default=sa.text("nextval('oe_com_type_oe_com_type_cd_seq'::regclass)"),
    )
    op.alter_column(
        "oe_com_type",
        "notitie",
        existing_type=sa.VARCHAR(length=2000),
        type_=sa.VARCHAR(length=4000),
        existing_comment="Notitieveld",
        existing_nullable=True,
    )
    op.alter_column(
        "oe_com_type",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        comment="Gebruikersnaam",
        existing_comment="User identification",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "oe_com_type",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "oe_com_type",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.alter_column(
        "oe_struct",
        "oe_struct_cd",
        existing_type=sa.INTEGER(),
        comment="Organisatie structuur code",
        existing_nullable=False,
    )
    op.alter_column(
        "oe_struct",
        "oe_cd_sub",
        existing_type=sa.INTEGER(),
        comment="Sub (child) organisatie code",
        existing_nullable=False,
    )
    op.alter_column(
        "oe_struct",
        "oe_cd_sup",
        existing_type=sa.INTEGER(),
        comment="Sup (parent) organisatie code",
        existing_nullable=False,
    )
    op.alter_column(
        "oe_struct",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        comment="Gebruikersnaam",
        existing_comment="User identification",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "oe_struct",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "oe_struct",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.create_table_comment(
        "oe_struct",
        "Hiërarchische structuur van organisaties wat resulteert in een sub(=child)-sup(=parent) relatie",
        existing_comment="Relatie van een bepaald type tussen twee organisatorische eenheden/instanties",
        schema=None,
    )
    op.drop_column("oe_struct", "osrt_cd")
    op.alter_column(
        "ond",
        "notitie",
        existing_type=sa.VARCHAR(length=2000),
        type_=sa.VARCHAR(length=4000),
        existing_comment="Notitieveld",
        existing_nullable=True,
    )
    op.alter_column(
        "ond",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        comment="Gebruikersnaam",
        existing_comment="User identification",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "ond",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
        comment="Tijdstip start datum",
        existing_comment="Tijdstip aanmaakdatum",
        existing_nullable=False,
    )
    op.create_table_comment(
        "ond", "Onderwerpen waar een besluit toebehoort", existing_comment="Onderwerpen tabel", schema=None
    )
    op.alter_column(
        "rge",
        "rge_cd",
        existing_type=sa.INTEGER(),
        comment="Regelingelement code",
        existing_nullable=False,
        existing_server_default=sa.text("nextval('rge_rge_cd_seq'::regclass)"),
    )
    op.alter_column(
        "rge",
        "re_link",
        existing_type=sa.VARCHAR(length=300),
        comment="Link naar wet of regelgeving",
        existing_comment="(Deep) link naar wet of regelgeving",
        existing_nullable=True,
    )
    op.alter_column(
        "rge",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        comment="Gebruikersnaam",
        existing_comment="User identification",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "rge",
        "ts_mut",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_comment="Tijdstip laatste mutatie",
        existing_nullable=False,
    )
    op.alter_column(
        "rge",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "rge",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rge",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.alter_column(
        "rge",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "rge",
        "ts_mut",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_comment="Tijdstip laatste mutatie",
        existing_nullable=False,
    )
    op.alter_column(
        "rge",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        comment="User identification",
        existing_comment="Gebruikersnaam",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "rge",
        "re_link",
        existing_type=sa.VARCHAR(length=300),
        comment="(Deep) link naar wet of regelgeving",
        existing_comment="Link naar wet of regelgeving",
        existing_nullable=True,
    )
    op.alter_column(
        "rge",
        "rge_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Regelingelement code",
        existing_nullable=False,
        existing_server_default=sa.text("nextval('rge_rge_cd_seq'::regclass)"),
    )
    op.create_table_comment(
        "ond", "Onderwerpen tabel", existing_comment="Onderwerpen waar een besluit toebehoort", schema=None
    )
    op.alter_column(
        "ond",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2023-12-01 00:00:00+00'::timestamp with time zone"),
        comment="Tijdstip aanmaakdatum",
        existing_comment="Tijdstip start datum",
        existing_nullable=False,
    )
    op.alter_column(
        "ond",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        comment="User identification",
        existing_comment="Gebruikersnaam",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "ond",
        "notitie",
        existing_type=sa.VARCHAR(length=4000),
        type_=sa.VARCHAR(length=2000),
        existing_comment="Notitieveld",
        existing_nullable=True,
    )
    op.add_column("oe_struct", sa.Column("osrt_cd", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table_comment(
        "oe_struct",
        "Relatie van een bepaald type tussen twee organisatorische eenheden/instanties",
        existing_comment="Hiërarchische structuur van organisaties wat resulteert in een sub(=child)-sup(=parent) relatie",
        schema=None,
    )
    op.alter_column(
        "oe_struct",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.alter_column(
        "oe_struct",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "oe_struct",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        comment="User identification",
        existing_comment="Gebruikersnaam",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "oe_struct",
        "oe_cd_sup",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Sup (parent) organisatie code",
        existing_nullable=False,
    )
    op.alter_column(
        "oe_struct",
        "oe_cd_sub",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Sub (child) organisatie code",
        existing_nullable=False,
    )
    op.alter_column(
        "oe_struct",
        "oe_struct_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Organisatie structuur code",
        existing_nullable=False,
    )
    op.alter_column(
        "oe_com_type",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.alter_column(
        "oe_com_type",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "oe_com_type",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        comment="User identification",
        existing_comment="Gebruikersnaam",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "oe_com_type",
        "notitie",
        existing_type=sa.VARCHAR(length=4000),
        type_=sa.VARCHAR(length=2000),
        existing_comment="Notitieveld",
        existing_nullable=True,
    )
    op.alter_column(
        "oe_com_type",
        "oe_com_type_cd",
        existing_type=sa.INTEGER(),
        comment="Kanaal type code",
        existing_comment="Communicatiekanaal type code",
        existing_nullable=False,
        existing_server_default=sa.text("nextval('oe_com_type_oe_com_type_cd_seq'::regclass)"),
    )
    op.add_column("oe", sa.Column("oe_type_cd", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table_comment(
        "oe",
        "Organisatorische eenheid/instantie of soort van organisatorische entiteit",
        existing_comment="Organisatorische eenheid en of instantie",
        schema=None,
    )
    op.alter_column(
        "oe",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.alter_column(
        "oe",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "oe",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        comment="User identification",
        existing_comment="Gebruikersnaam",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "oe",
        "telefoon",
        existing_type=sa.VARCHAR(length=30),
        comment="Telefoonnummer (volledig)",
        existing_comment="Telefoonnummer",
        existing_nullable=True,
    )
    op.alter_column(
        "oe",
        "straat",
        existing_type=sa.VARCHAR(length=30),
        comment="Straatnaam cf. postcode tabel of 'Postbus'",
        existing_comment="Straatnaam",
        existing_nullable=True,
    )
    op.alter_column(
        "oe",
        "naam_spraakgbr",
        existing_type=sa.VARCHAR(length=255),
        comment="Naam die gebruikt voor in het 'normale'  spraakgebruik",
        existing_comment="Naam die gebruikt voor in het 'normale' spraakgebruik",
        existing_nullable=False,
    )
    op.alter_column(
        "oe",
        "lidw_sgebr",
        existing_type=sa.VARCHAR(length=12),
        comment="Lidwoord van de organisatie (de, het, een)",
        existing_comment="Lidwoord van de organisatie",
        existing_nullable=True,
    )
    op.alter_column(
        "oe",
        "ibron_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Informatiebron code",
        existing_nullable=True,
    )
    op.alter_column(
        "oe",
        "huisnummer",
        existing_type=sa.VARCHAR(length=10),
        comment="Huisnummer cf. postcode tabel",
        existing_comment="Huisnummer",
        existing_nullable=True,
    )
    op.alter_column(
        "oe",
        "fax",
        existing_type=sa.VARCHAR(length=30),
        comment="Faxnummer (volledig)",
        existing_comment="Faxnummer",
        existing_nullable=True,
    )
    op.alter_column("oe", "oe_upc", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "oe",
        "oe_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Organisatie code",
        existing_nullable=False,
        existing_server_default=sa.text("nextval('oe_oe_cd_seq'::regclass)"),
    )
    op.create_table_comment(
        "ibron",
        "Registratie waar de gegevens afkomstig van zijn.",
        existing_comment="register waar de gegevens afkomstig van zijn",
        schema=None,
    )
    op.alter_column(
        "ibron",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.alter_column(
        "ibron",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "ibron",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        comment="User identification",
        existing_comment="Gebruikersnaam",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "ibron",
        "omschrijving",
        existing_type=sa.VARCHAR(length=80),
        comment="Omschrijving/naam van de bron",
        existing_comment="Omschrijving van de bron",
        existing_nullable=False,
    )
    op.alter_column(
        "ibron",
        "oe_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Organisatie code",
        existing_nullable=True,
    )
    op.alter_column(
        "ibron",
        "ibron_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Informatiebron code",
        existing_nullable=False,
        existing_server_default=sa.text("nextval('ibron_ibron_cd_seq'::regclass)"),
    )
    op.alter_column(
        "gst_type",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gst_type",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gst_type",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        comment="User identification",
        existing_comment="Gebruikersnaam",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "gst_type",
        "gstt_pp",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Push of pull van een gegevenstroom type",
        existing_nullable=True,
    )
    op.alter_column(
        "gst_type",
        "gstt_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Gegevensstroomtype code",
        existing_nullable=False,
    )
    op.drop_column("gst_type", "notitie")
    op.create_table_comment(
        "gst_gstt",
        "Relatie tussen gegevensstroom en gegevensstroomtype",
        existing_comment="Koppeling tussen gegevensstroom en gegevensstroomtype",
        schema=None,
    )
    op.alter_column(
        "gst_gstt",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gst_gstt",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gst_gstt",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        comment="User identification",
        existing_comment="Gebruikersnaam",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "gst_gstt",
        "gst_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Gegevensstroom code",
        existing_nullable=False,
    )
    op.alter_column(
        "gst_gstt",
        "gstt_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Gegevensstroomtype code",
        existing_nullable=False,
    )
    op.alter_column(
        "gst_gstt",
        "gst_gstt_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Gegevensstroom gegevensstroomtype code",
        existing_nullable=False,
    )
    op.drop_column("gst_gstt", "notitie")
    op.create_table_comment(
        "gst_gg_rge",
        "Relatie tussen gegevensstroom, gegevensgroep en wettelijke grondslag",
        existing_comment="Koppeling tussen gegevensstroom, gegevensgroep en regelingelemen",
        schema=None,
    )
    op.drop_index(op.f("ix_gst_gg_rge_rge_cd"), table_name="gst_gg_rge")
    op.drop_index(op.f("ix_gst_gg_rge_gst_cd"), table_name="gst_gg_rge")
    op.drop_index(op.f("ix_gst_gg_rge_gg_cd"), table_name="gst_gg_rge")
    op.alter_column(
        "gst_gg_rge",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gst_gg_rge",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gst_gg_rge",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        comment="User identification",
        existing_comment="Gebruikersnaam",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "gst_gg_rge",
        "rge_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Regelingelement code",
        existing_nullable=False,
    )
    op.alter_column(
        "gst_gg_rge",
        "gg_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Gegevensgroep code",
        existing_nullable=False,
    )
    op.alter_column(
        "gst_gg_rge",
        "gst_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Gegevensstroom code",
        existing_nullable=False,
    )
    op.alter_column(
        "gst_gg_rge",
        "gst_gg_rge_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Gegevensstroom gegevensgroep regelingelement code",
        existing_nullable=False,
    )
    op.create_table_comment(
        "gst",
        "Gegevensstromen tussen (soorten) organisatorische eenheden/instanties",
        existing_comment="Gegevensstroom die tussen bron- en bestemmingsorganisatorische eenheden loopt waarbij gegevensgroepen worden gedeeld",
        schema=None,
    )
    op.drop_index(op.f("ix_gst_gst_upc"), table_name="gst")
    op.alter_column(
        "gst",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gst",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gst",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        comment="User identification",
        existing_comment="Gebruikersnaam",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "gst",
        "oe_best",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Organisatorische eenheid bestemming",
        existing_nullable=False,
    )
    op.alter_column(
        "gst",
        "oe_bron",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Organisatorische eenheid bron",
        existing_nullable=False,
    )
    op.alter_column(
        "gst",
        "omschrijving",
        existing_type=sa.VARCHAR(length=255),
        comment="Omschrijving/Naam gegevensstroom",
        existing_comment="Omschrijving van de gegevensstroom",
        existing_nullable=False,
    )
    op.alter_column(
        "gst",
        "gst_upc",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Uniforme product code dat hoort bij een gegevensstroom",
        existing_nullable=False,
    )
    op.alter_column(
        "gst",
        "gst_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Gegevensstroom code",
        existing_nullable=False,
    )
    op.create_table_comment(
        "gg_struct",
        "Relatie tussen gegevensgroepen van een bepaalse soort",
        existing_comment="Hiërarchische structuur van gegevensgroepen wat resulteert in een sub(=child)-sup(=parent) relatie",
        schema=None,
    )
    op.alter_column(
        "gg_struct",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gg_struct",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gg_struct",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        comment="User identification",
        existing_comment="Gebruikersnaam",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "gg_struct",
        "gg_cd_sup",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Super (parent) gegevensgroep code",
        existing_nullable=False,
    )
    op.alter_column(
        "gg_struct",
        "gg_cd_sub",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Sub (child) gegevensgroep code",
        existing_nullable=False,
    )
    op.alter_column(
        "gg_struct",
        "gg_struct_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Gegevensgroepen structuur code",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_gg_gg_upc"), table_name="gg")
    op.alter_column(
        "gg",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gg",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "gg",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        comment="User identification",
        existing_comment="Gebruikersnaam",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "gg",
        "notitie",
        existing_type=sa.VARCHAR(length=4000),
        type_=sa.VARCHAR(length=2000),
        comment="Kort toelichting ter duiding van een gegevensgroep",
        existing_comment="Notitieveld",
        existing_nullable=True,
    )
    op.alter_column(
        "gg",
        "koepel",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Wel of geen koepel",
        existing_nullable=True,
    )
    op.alter_column(
        "gg",
        "sort_key",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Sorteer volgorde van de koepelgegevensgroep in een besluit",
        existing_nullable=True,
    )
    op.alter_column(
        "gg",
        "omschrijving_uitgebreid",
        existing_type=sa.VARCHAR(length=4000),
        comment="Notitieveld",
        existing_comment="Uitgebreide omschrijving van de gegevensgroep",
        existing_nullable=False,
    )
    op.alter_column(
        "gg",
        "omschrijving",
        existing_type=sa.VARCHAR(length=4000),
        comment="Omschrijving/Naam van de gegevensgroep",
        existing_comment="Naam van de gegevensgroep",
        existing_nullable=False,
    )
    op.alter_column(
        "gg",
        "gg_upc",
        existing_type=sa.INTEGER(),
        nullable=True,
        comment=None,
        existing_comment="Uniforme product code dat hoort bij een gegevensgroep",
    )
    op.alter_column(
        "gg",
        "gg_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Gegevensgroep code",
        existing_nullable=False,
    )
    op.drop_table_comment(
        "evtp_version",
        existing_comment="Versie van een ieder besluit met een bepaalde status die aanleiding kunnen zijn voor het vastleggen of uitwisselen van gegevensgroepen",
        schema=None,
    )
    op.create_foreign_key("evpt_evptsup_fk", "evtp_version", "evtp", ["evtp_cd_sup"], ["evtp_cd"], ondelete="CASCADE")
    op.create_index("ix_evtp_version_evtp_cd", "evtp_version", ["evtp_cd"], unique=False)
    op.alter_column(
        "evtp_version",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.alter_column(
        "evtp_version",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "evtp_version",
        "ts_mut",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip laatste mutatie",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "evtp_version",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        comment="User identification",
        existing_comment="Gebruikersnaam",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "evtp_version",
        "notitie",
        existing_type=sa.VARCHAR(length=4000),
        comment=None,
        existing_comment="Notitieveld",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_version",
        "id_publicatiestatus",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Publicatie nummer voor een besluit",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_version",
        "huidige_versie",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Wel of geen huidige versie van besluit",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "evtp_version",
        "soort_besluit",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Verschillende soorten officiële besluiten, mededelingen en documenten.",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_version",
        "lidw_soort_besluit",
        existing_type=sa.VARCHAR(length=12),
        comment=None,
        existing_comment="Lidwoord van het soort besluit",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_version",
        "oe_best",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Verantwoordelijke(=bestemming) organisatie die behoort tot dit besluit",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_version",
        "gebr_dl",
        existing_type=sa.VARCHAR(length=200),
        comment=None,
        existing_comment="Gebruiksdoel van het besluit",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_version",
        "aanleiding",
        existing_type=sa.VARCHAR(length=2000),
        comment=None,
        existing_comment="Aanleiding van het nemen van een besluit",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_version",
        "omschrijving",
        existing_type=sa.VARCHAR(length=2000),
        comment=None,
        existing_comment="Omschrijving het besluit",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_version",
        "evtp_nm",
        existing_type=sa.VARCHAR(length=200),
        comment=None,
        existing_comment="Naam van besluit",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_version",
        "evtp_cd_sup",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Koepelbesluit",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_version",
        "versie_nr",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Versie nummer van het besluit",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_version",
        "evtp_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Besluit code",
        existing_nullable=False,
    )
    op.create_table_comment(
        "evtp_ond",
        "Relatie tussen onderwerpen en besluiten",
        existing_comment="Koppeling tussen onderwerpen en besluiten",
        schema=None,
    )
    op.create_foreign_key("evptond_evtp_fk", "evtp_ond", "evtp", ["evtp_cd"], ["evtp_cd"])
    op.alter_column(
        "evtp_ond",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2023-12-01 00:00:00+00'::timestamp with time zone"),
        comment="Tijdstip aanmaakdatum",
        existing_comment="Tijdstip start datum",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_ond",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        comment="User identification",
        existing_comment="Gebruikersnaam",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "evtp_ond",
        "notitie",
        existing_type=sa.VARCHAR(length=4000),
        type_=sa.VARCHAR(length=2000),
        existing_comment="Notitieveld",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_ond",
        "evtp_cd",
        existing_type=sa.INTEGER(),
        comment="Event type code",
        existing_comment="Besluit code",
        existing_nullable=False,
    )
    op.create_table_comment(
        "evtp_oe_com_type",
        "Relatie tussen besluit en bestemming organiatie communicatie kanaal",
        existing_comment="Koppeling tussen een besluit en bestemmingsorganisatie communicatie kanaal",
        schema=None,
    )
    op.create_foreign_key("evtp_oe_com_evtp_fk", "evtp_oe_com_type", "evtp", ["evtp_cd"], ["evtp_cd"])
    op.alter_column(
        "evtp_oe_com_type",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.alter_column(
        "evtp_oe_com_type",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "evtp_oe_com_type",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        comment="User identification",
        existing_comment="Gebruikersnaam",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "evtp_oe_com_type",
        "link",
        existing_type=sa.VARCHAR(length=2000),
        comment="Hyperlink waar de burger de uitkoms van het besluit ontvangt",
        existing_comment="Hyperlink waar de burger de uitkomst van het besluit ontvangt",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_oe_com_type",
        "oe_com_type_cd",
        existing_type=sa.INTEGER(),
        comment="Kanaal type code",
        existing_comment="Communicatiekanaal type code",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_oe_com_type",
        "evtp_cd",
        existing_type=sa.INTEGER(),
        comment="Eventtype code",
        existing_comment="Besluit code",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_oe_com_type",
        "evtp_oe_com_type_cd",
        existing_type=sa.INTEGER(),
        comment="Besluit organisatie code",
        existing_comment="Besluit bestemmingsorganisatie communicatie kanaal code",
        existing_nullable=False,
    )
    op.drop_column("evtp_oe_com_type", "notitie")
    op.create_table_comment(
        "evtp_gst",
        "Cross-reference tusen gegevensstroom en eventtypen",
        existing_comment="Koppeling tussen een besluit en de gegevensstromen",
        schema=None,
    )
    op.create_foreign_key("evtpgst_evtp_fk", "evtp_gst", "evtp", ["evtp_cd"], ["evtp_cd"])
    op.alter_column(
        "evtp_gst",
        "ts_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip einde datum",
        existing_nullable=False,
        existing_server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
    )
    op.alter_column(
        "evtp_gst",
        "ts_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Tijdstip start datum",
        existing_nullable=False,
        existing_server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
    )
    op.alter_column(
        "evtp_gst",
        "user_nm",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        comment="User identification",
        existing_comment="Gebruikersnaam",
        existing_server_default=sa.text("'ICTU'::character varying"),
    )
    op.alter_column(
        "evtp_gst",
        "notitie",
        existing_type=sa.VARCHAR(length=4000),
        comment="Notitie",
        existing_comment="Notitieveld",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_gst",
        "sort_key",
        existing_type=sa.INTEGER(),
        comment="Sorteersleutel",
        existing_comment="Sorteersleutel om de gegevensstromen blokken te ordenen binnen een koepelgegeven van een besluit",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_gst",
        "conditie",
        existing_type=sa.VARCHAR(length=4000),
        comment="Toelichting van een conditie waaronder de gegevensstroom plaatsvindt, bijvoorbeeld ziek worden, wel of geen werk hebben, etc ",
        existing_comment="Toelichting van een conditie waaronder de gegevensstroom plaatsvindt, bijvoorbeeld ziek worden, wel of geen werk hebben, etc.",
        existing_nullable=True,
    )
    op.alter_column(
        "evtp_gst",
        "gst_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Gegevensstroom code",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_gst",
        "evtp_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Besluit code",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_gst",
        "evtp_gst_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Besluit gegevensstroom code",
        existing_nullable=False,
    )
    op.create_foreign_key("evtp_acc_cd_fk", "evtp_acc", "evtp", ["evtp_cd"], ["evtp_cd"])
    op.alter_column(
        "evtp_acc",
        "bestand_acc_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Bestandsaccordering code",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_acc",
        "volg_nr",
        existing_type=sa.INTEGER(),
        comment="Volgnummer",
        existing_comment="Volgnummer mocht een accordering uit meerdere bestaan",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_acc",
        "oe_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Organisatie code",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_acc",
        "evtp_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Besluit code",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp_acc",
        "evtp_acc_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Accordering code",
        existing_nullable=False,
    )
    op.drop_column("evtp_acc", "user_nm")
    op.create_table_comment(
        "evtp",
        "Relevante soorten gebeurtenissen die aanleiding (kunnen) zijn voor het vastleggen of uitwisslen van gegevens(groepen)",
        existing_comment="Alle unieke besluiten met zijn bijgehorende uniforme product code nummer",
        schema=None,
    )
    op.drop_index(op.f("ix_evtp_evtp_upc"), table_name="evtp")
    op.alter_column(
        "evtp",
        "evtp_upc",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Uniforme product code dat hoort bij een besluit",
        existing_nullable=False,
    )
    op.alter_column(
        "evtp",
        "evtp_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Besluit code",
        existing_nullable=False,
        existing_server_default=sa.text("nextval('evtp_evtp_cd_seq'::regclass)"),
    )
    # op.add_column(
    #     "bestand_acc",
    #     sa.Column(
    #         "ts_create",
    #         postgresql.TIMESTAMP(timezone=True),
    #         autoincrement=False,
    #         nullable=False,
    #         comment="Tijdstip accordering",
    #     ),
    # )
    op.alter_column(
        "bestand_acc",
        "bestand_verwijzing",
        existing_type=sa.VARCHAR(length=255),
        comment="Betandsverwijzing",
        existing_comment="Bestandsverwijzing",
        existing_nullable=False,
    )
    op.alter_column(
        "bestand_acc",
        "omschrijving",
        existing_type=sa.VARCHAR(length=255),
        comment="Bestand omschrijving",
        existing_comment="Bestandsomschrijving",
        existing_nullable=True,
    )
    op.alter_column(
        "bestand_acc",
        "volg_nr",
        existing_type=sa.INTEGER(),
        comment="Volgnummer",
        existing_comment="Volgnummer voor meerdere bestanden bij een accordering",
        existing_nullable=False,
    )
    op.alter_column(
        "bestand_acc",
        "bestand_acc_cd",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Bestandsaccordering code",
        existing_nullable=False,
    )
    op.drop_column("bestand_acc", "user_nm")
    op.create_table(
        "oe_type",
        sa.Column(
            "omschrijving",
            sa.VARCHAR(length=80),
            autoincrement=False,
            nullable=False,
            comment="Omschrijving organisatorische eenheid of entiteit",
        ),
        sa.Column(
            "user_nm",
            sa.VARCHAR(length=30),
            server_default=sa.text("'ICTU'::character varying"),
            autoincrement=False,
            nullable=False,
            comment="User identification",
        ),
        sa.Column("notitie", sa.VARCHAR(length=4000), autoincrement=False, nullable=True, comment="Notitieveld"),
        sa.Column(
            "ts_mut",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
            comment="Tijdstip laatste mutatie",
        ),
        sa.Column("oe_type_cd", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "ts_start",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ts_end",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("oe_type_cd", name="oe_type_pkey"),
        comment="Type organisatorische eenheid",
    )
    op.create_foreign_key("oe_oet_fk", "oe", "oe_type", ["oe_type_cd"], ["oe_type_cd"])
    op.create_table(
        "oe_struct_rolt",
        sa.Column(
            "omschrijving",
            sa.VARCHAR(length=80),
            autoincrement=False,
            nullable=False,
            comment="Omschrijving van het roltype",
        ),
        sa.Column(
            "user_nm",
            sa.VARCHAR(length=30),
            server_default=sa.text("'ICTU'::character varying"),
            autoincrement=False,
            nullable=False,
            comment="User identification",
        ),
        sa.Column("notitie", sa.VARCHAR(length=4000), autoincrement=False, nullable=True, comment="Notitieveld"),
        sa.Column(
            "ts_mut",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
            comment="Tijdstip laatste mutatie",
        ),
        sa.Column("osrt_cd", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "ts_start",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ts_end",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("osrt_cd", name="oe_struct_rolt_pkey"),
        comment="Soort relatie die organisatorische eenheden/instanties met elkaar kunnen hebben",
    )
    op.create_foreign_key("oes_osrt_fk", "oe_struct", "oe_struct_rolt", ["osrt_cd"], ["osrt_cd"])
    op.create_table(
        "tabellenvoorbeheer",
        sa.Column("tabelnaam", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("tabelcomment", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.Column("tabellabelkort", sa.VARCHAR(length=60), autoincrement=False, nullable=True),
        sa.Column("tabellabellang", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("indtabelinbeheer", sa.INTEGER(), server_default=sa.text("1"), autoincrement=False, nullable=False),
        sa.Column("notitie", sa.VARCHAR(length=4000), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("tabelnaam", name="idx_16555_primary"),
        comment="Tabellen in inzage die beheerd kunnen worden",
    )
    op.create_table(
        "rubriekenvoorbeheer",
        sa.Column(
            "rubrieknaam",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="Naam van de rubriek in de database",
        ),
        sa.Column(
            "tabelnaam",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="Naam van de tabel in de database",
        ),
        sa.Column(
            "rubriekcomment",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
            comment="Rubriek comment in de database",
        ),
        sa.Column(
            "rubrieklabelkort",
            sa.VARCHAR(length=60),
            autoincrement=False,
            nullable=True,
            comment="Rubriek label (kort) voor op het scherm",
        ),
        sa.Column(
            "rubrieklabellang",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="Rubriek label (lang) voor op het scherm",
        ),
        sa.Column(
            "indrubriekinbeheer",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
            comment="Indicator of desbetreffende rubriek opgenomen moet worden in het beheerscherm",
        ),
        sa.Column(
            "rubriekdefaultwaarde",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
            comment="Standaard waarde van de rubriek",
        ),
        sa.Column(
            "rubriekismagleegzijn",
            sa.VARCHAR(length=1),
            autoincrement=False,
            nullable=False,
            comment="Indicator of de rubriek leeg (null) gelaten mag worden",
        ),
        sa.Column(
            "rubriekdataformat",
            sa.VARCHAR(length=45),
            autoincrement=False,
            nullable=True,
            comment="Het data formaat van de rubriek in de database",
        ),
        sa.Column(
            "rubriekissleutel",
            sa.VARCHAR(length=1),
            autoincrement=False,
            nullable=True,
            comment="Indicator of de rubriek onderdeel uitmaakt van een sleutel",
        ),
        sa.Column(
            "rubriekvolgordenummer",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Volgorde van de rubriek voor het tonen op het beheerscherm",
        ),
        sa.Column("rubriekmutatietype", sa.VARCHAR(length=1), autoincrement=False, nullable=True),
        sa.Column("rubriekmutatietypeomschrijving", sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
        sa.Column(
            "rubriekreferentie",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
            comment="Tabel.Kolom waarnaar deze rubriek verwijst middels een foreign key",
        ),
        sa.Column("notitie", sa.VARCHAR(length=4000), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["tabelnaam"], ["tabellenvoorbeheer.tabelnaam"], name="rubriektabel_fk"),
        sa.PrimaryKeyConstraint("rubrieknaam", "tabelnaam", name="idx_16546_primary"),
        comment="Rubrieken in inzage die beheerd kunnen worden",
    )
    op.create_index("ix_rubriekenvoorbeheer_tabelnaam", "rubriekenvoorbeheer", ["tabelnaam"], unique=False)
    op.create_index("ix_tabellenvoorbeheer_tabelnaam", "tabellenvoorbeheer", ["tabelnaam"], unique=False)
    op.create_table(
        "persoon",
        sa.Column("user_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("naam", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("user_id", name="persoon_pkey"),
        sa.UniqueConstraint("naam", name="persoon_naam_key"),
    )
    # ### end Alembic commands ###
