"""removed columns from oe

Revision ID: 8fdcf5c0da84
Revises: 5373d4030cf2
Create Date: 2024-03-11 10:32:29.800204

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8fdcf5c0da84"
down_revision = "5373d4030cf2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE oe DROP CONSTRAINT IF EXISTS oe_rge_fk")
    op.drop_column("oe", "fax")
    op.drop_column("oe", "rge_cd")
    op.drop_column("oe", "id_ext_bron")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oe",
        sa.Column(
            "id_ext_bron",
            sa.VARCHAR(length=12),
            autoincrement=False,
            nullable=True,
            comment="De code of het id die gebruikt wordt bij de externe bron waar de content van afkomstig is",
        ),
    )
    op.add_column("oe", sa.Column("rge_cd", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(
        "oe", sa.Column("fax", sa.VARCHAR(length=30), autoincrement=False, nullable=True, comment="Faxnummer")
    )
    op.create_foreign_key("oe_rge_fk", "oe", "rge", ["rge_cd"], ["rge_cd"])
    # ### end Alembic commands ###
