"""add_gg_evtp_sort table

Revision ID: f44ff3a38f3f
Revises: be5a4e2196e5
Create Date: 2024-04-02 13:47:51.098316

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f44ff3a38f3f"
down_revision = "be5a4e2196e5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gg_evtp_sort",
        sa.Column(
            "gg_evtp_sort_cd", sa.Integer(), nullable=False, comment="Koepelgegevensgroep-Besluit sortering code"
        ),
        sa.Column("gg_cd", sa.Integer(), nullable=False, comment="Koepelgegevensgroep code"),
        sa.Column("evtp_cd", sa.Integer(), nullable=False, comment="Besluit code"),
        sa.Column(
            "sort_key",
            sa.Integer(),
            nullable=False,
            comment="Sorteer volgorde van de koepelgegevensgroep in een besluit",
        ),
        sa.Column("notitie", sa.VARCHAR(length=4000), nullable=True, comment="Notitieveld"),
        sa.Column("user_nm", sa.VARCHAR(length=30), server_default="ICTU", nullable=True, comment="Gebruikersnaam"),
        sa.Column(
            "ts_mut",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Tijdstip laatste mutatie",
        ),
        sa.Column(
            "ts_start",
            sa.DateTime(timezone=True),
            server_default=sa.text("'2023-01-01 00:00:00+00'::timestamp with time zone"),
            nullable=False,
            comment="Tijdstip start datum",
        ),
        sa.Column(
            "ts_end",
            sa.DateTime(timezone=True),
            server_default=sa.text("'9999-12-31 23:59:59.999999+00'::timestamp with time zone"),
            nullable=False,
            comment="Tijdstip einde datum",
        ),
        sa.ForeignKeyConstraint(["gg_cd"], ["gg.gg_cd"], name=op.f("fk_gg_evtp_sort_gg_cd_gg")),
        sa.ForeignKeyConstraint(["evtp_cd"], ["evtp.evtp_cd"], name=op.f("fk_gg_evtp_sort_evtp_cd_evtp")),
        sa.PrimaryKeyConstraint("gg_evtp_sort_cd", name=op.f("pk_gg_evtp_sort")),
        comment="sort_key gg op basis van evtp",
    )


def downgrade() -> None:
    op.drop_table("gg_evtp_sort")
    # ### end Alembic commands ###
